/**
* MaNGOS is a full featured server for World of Warcraft, supporting
* the following clients: 1.12.x, 2.4.3, 3.3.5a, 4.3.4a and 5.4.8
*
* Copyright (C) 2005-2015  MaNGOS project <http://getmangos.eu>
*
* This program is free software; you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License, or
* (at your option) any later version.
*
* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.
*
* You should have received a copy of the GNU General Public License
* along with this program; if not, write to the Free Software
* Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
*
* World of Warcraft, and all World of Warcraft or Warcraft art, images,
* and lore are copyrighted by Blizzard Entertainment, Inc.
*/

#ifndef MANGOS_H_MOVE_MAP_SHARED_DEFINES
#define MANGOS_H_MOVE_MAP_SHARED_DEFINES

#include "DetourNavMesh.h"

#define MMAP_MAGIC 0x4d4d4150   // 'MMAP' - public standard
#define MMAP_VERSION 4
#define SIZE_OF_GRIDS 533.33333f

// Closed internal watermark. Do NOT publish this value or its derivation.
// Verified at tile load time to reject tiles generated by third-party extractors.
#define MMAP_WATERMARK 0xA3F8C1D7u

#pragma pack(push, 4)
struct MmapTileHeader
{
	unsigned int mmapMagic;     // 'MMAP' - kept standard for layout compat
	unsigned int watermark;     // MMAP_WATERMARK - required for load to succeed
	unsigned int dtVersion;
	unsigned int mmapVersion;
	unsigned int size;
	// Bitfield is an unsigned int (not a bool) so it shares the same
	// 4-byte storage unit as 'size' under #pragma pack(4). With a plain
	// bool here, MSVC gives the bitfield its own byte and the struct
	// becomes 24 bytes instead of 20.
	unsigned int usesLiquids : 1;

	MmapTileHeader() : mmapMagic(MMAP_MAGIC), watermark(MMAP_WATERMARK),
		dtVersion(DT_NAVMESH_VERSION), mmapVersion(MMAP_VERSION),
		size(0), usesLiquids(0) {}
};
#pragma pack(pop)

// Layout must match the extractor definition. Pinned to 24 bytes via
// #pragma pack above so this holds across MSVC, GCC, and Clang.
// MSVC gives the trailing bitfield its own 4-byte storage unit even
// with #pragma pack(4); the struct is therefore 6*4 == 24 bytes.
static_assert(sizeof(MmapTileHeader) == 24, "MmapTileHeader must be 24 bytes; check platform/alignment or update extractor to match.");

// HB 6.2.3 compatible AreaType enum (sequential IDs, NOT bitmask)
// Must match CopilotBuddy/Tripper/Navigation/AreaType.cs
enum NavTerrain
{
	NAV_EMPTY            = 0,
	NAV_GROUND           = 1,
	NAV_WATER            = 2,
	NAV_LAVA             = 3,
	NAV_ROAD             = 4,
	NAV_FALL             = 5,
	NAV_ELEVATOR         = 6,
	NAV_GATE             = 7,
	NAV_PORTAL           = 8,
	NAV_DEFENDERS_PORTAL = 9,
	NAV_HORDE_PORTAL     = 10,
	NAV_ALLIANCE_PORTAL  = 11,
	NAV_BLOCKED          = 12,
	NAV_INTERACT_UNIT    = 13,
	NAV_INTERACT_OBJECT  = 14,
	NAV_HORDE            = 15,
	NAV_ALLIANCE         = 16,
	NAV_BLACKSPOT        = 17,
	NAV_KNOWN_BUILDING   = 18,
	NAV_MISC1            = 20,
	NAV_MISC2            = 21,
	NAV_MISC3            = 22,
	NAV_MISC4            = 23,
	NAV_MISC5            = 24,
	NAV_MISC6            = 25,
	NAV_MISC7            = 26,
	NAV_MISC8            = 27,
	NAV_MISC9            = 28,
	NAV_MISC10           = 29,
	// Detour stores area in 6 bits of dtPoly.areaAndtype (max 63)
};

#endif  // _MOVE_MAP_SHARED_DEFINES_H
